// Generates src/bravura-font.ts by base64-encoding the bundled Bravura woff2.
// Run as part of build/dev so the embedded font stays in sync with font/.
import fs from "fs";

const woff2 = fs.readFileSync("font/Bravura.woff2").toString("base64");
const out =
	"// AUTO-GENERATED by scripts/gen-font.mjs — do not edit.\n" +
	"// Bravura SMuFL font (SIL OFL 1.1), base64 woff2, embedded so the plugin\n" +
	"// ships as 3 files (main.js + manifest.json + styles.css) for BRAT.\n" +
	`export const BRAVURA_WOFF2_BASE64 = ${JSON.stringify(woff2)};\n`;

fs.writeFileSync("src/bravura-font.ts", out);
console.log(`wrote src/bravura-font.ts (${woff2.length} base64 chars)`);
